### ISSUE TITLE
RuntimeError: Can't find any UDC

### ISSUE THREAD

**Issue by lukedoomer** [Prototyped/pikvm-container#1]
```
docker logs pikvm

[  OK  ] Started PiKVM - The KVMD persistent storage manager.
[  OK  ] Started PiKVM - Web terminal (ttyd).
         Starting User Login Management...
         Starting Permit User Sessions...
[FAILED] Failed to start Clean up kvmd USB gadget..
See 'systemctl status cleanup-usb-gadget.service' for details.
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Finished Permit User Sessions.
[  OK  ] Started Console Getty.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started User Login Management.
[FAILED] Failed to start PiKVM - OTG setup.
See 'systemctl status kvmd-otg.service' for details.
[  OK  ] Started PiKVM - The main daemon.
         Starting PiKVM - HTTP entrypoint...

Welcome to PiKVM - The Open Source KVM over IP on Raspberry Pi
Arch Linux ARM 6.1.21-v8+ (console)
IP: 172.17.0.2
```
```
[root@pikvm /]# journalctl -ru kvmd-otg.service

Jan 15 01:28:25 pikvm systemd[1]: Failed to start PiKVM - OTG setup.
Jan 15 01:28:25 pikvm systemd[1]: kvmd-otg.service: Failed with result 'exit-code'.
Jan 15 01:28:25 pikvm systemd[1]: kvmd-otg.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 01:28:25 pikvm kvmd-otg[194]: RuntimeError: Can't find any UDC
Jan 15 01:28:25 pikvm kvmd-otg[194]:     raise RuntimeError("Can't find any UDC")
Jan 15 01:28:25 pikvm kvmd-otg[194]:   File "/usr/lib/python3.11/site-packages/kvmd/usb.py", line 34, in find_udc
Jan 15 01:28:25 pikvm kvmd-otg[194]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 15 01:28:25 pikvm kvmd-otg[194]:     udc = usb.find_udc(config.otg.udc)
Jan 15 01:28:25 pikvm kvmd-otg[194]:   File "/usr/lib/python3.11/site-packages/kvmd/apps/otg/__init__.py", line 207, in _cmd_start
Jan 15 01:28:25 pikvm kvmd-otg[194]:     options.cmd(config)
Jan 15 01:28:25 pikvm kvmd-otg[194]:   File "/usr/lib/python3.11/site-packages/kvmd/apps/otg/__init__.py", line 348, in main
Jan 15 01:28:25 pikvm kvmd-otg[194]:              ^^^^^^
Jan 15 01:28:25 pikvm kvmd-otg[194]:     sys.exit(main())
Jan 15 01:28:25 pikvm kvmd-otg[194]:   File "/usr/bin/kvmd-otg", line 8, in <module>
Jan 15 01:28:25 pikvm kvmd-otg[194]: Traceback (most recent call last):
Jan 15 01:28:23 pikvm systemd[1]: Starting PiKVM - OTG setup...
````

![143783159-11e1a3c5-5652-4f14-8c00-3e989580c8d8](https://github.com/Prototyped/pikvm-container/assets/18679207/f9653601-42b9-4db4-a804-9427954b0710)

**Comment by Prototyped** [comment]
This happens when you start up the Raspberry Pi without correctly setting up the peripheral-mode overlay and/or not connecting the OTG port (which, on the Raspberry Pi 4, happens to be the power port -- hence the need for a data-power splitter) to the device to control.

Make sure you've set up the host correctly: https://github.com/Prototyped/pikvm-container#host-setup

That error is basically kvmd-otg complaining that it cannot find the USB host connected to the OTG port so it can emulate a USB keyboard and mouse. And once it fails, the kvmd UI process also fails.

**Comment by lukedoomer** [comment]
I do have a working power splitter. Actually I have been using it with original pikvm sd image for a long time.

**Comment by Prototyped** [comment]
This is what it looks like on my Raspberry Pi 4:

```shell
% docker exec -it pikvm bash
[root@pikvm /]# journalctl -xeu kvmd-otg.service
Jan 15 02:18:07 pikvm systemd[1]: Starting PiKVM - OTG setup...
░░ Subject: A start job for unit kvmd-otg.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit kvmd-otg.service has begun execution.
░░
░░ The job identifier is 92.
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- Using UDC fe980000.usb
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- Creating gadget 'kvmd' ...
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/idVendor
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/idProduct
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/bcdUSB
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/bcdDevice
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/manufacturer
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/product
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/strings/0x409/serialnumber
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/strings/0x409
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/strings/0x409/configuration
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/configs/c.1/MaxPower
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /run/kvmd/otg
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- ===== HID-Keyboard =====
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/no_out_endpoint
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/protocol
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/subclass
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/report_length
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0/report_desc
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- SYMLINK - /sys/kernel/config/usb_gadget/kvmd/configs/c.1/hid.usb0 --> /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb0
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /run/kvmd/otg/hid.usb0@meta.json
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- ===== HID-Mouse =====
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/no_out_endpoint
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/protocol
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/subclass
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/report_length
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1/report_desc
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- SYMLINK - /sys/kernel/config/usb_gadget/kvmd/configs/c.1/hid.usb1 --> /sys/kernel/config/usb_gadget/kvmd/functions/hid.usb1
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /run/kvmd/otg/hid.usb1@meta.json
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- ===== Preparing complete =====
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- Enabling the gadget ...
Jan 15 02:18:08 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- WRITE --- /sys/kernel/config/usb_gadget/kvmd/UDC
Jan 15 02:18:11 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- CHOWN --- kvmd - /sys/kernel/config/usb_gadget/kvmd/UDC
Jan 15 02:18:11 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- CHOWN --- kvmd - /sys/kernel/config/usb_gadget/kvmd/configs/c.1
Jan 15 02:18:11 pikvm kvmd-otg[219]: kvmd.apps.otg                     INFO --- Ready to work
Jan 15 02:18:11 pikvm systemd[1]: Finished PiKVM - OTG setup.
░░ Subject: A start job for unit kvmd-otg.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit kvmd-otg.service has finished successfully.
░░
░░ The job identifier is 92.
```

**Comment by Prototyped** [comment]
kvmd-otg basically creates a USB gadget under /sys/kernel/config/usb_gadget/kvmd.

```
[root@pikvm /]# cat /sys/kernel/config/usb_gadget/kvmd/UDC
fe980000.usb
```

Can you check whether you have access to configfs (/sys/kernel/config) from inside the container?

**Comment by lukedoomer** [comment]
you are right I missed the configuration `dtoverlay=dwc2,dr_mode=peripheral`
I have added the line and produced some other errors

no `usb_gadget/kvmd/UDC`
```
docker exec -it pikvm ls /sys/kernel/config

device-tree
```
no `dwc2 fe980000.usb: bound driver configfs-gadget.kvmd`
```
[root@pikvm /]# dmesg | grep dwc2
[    5.969422] dwc2 fe980000.usb: supply vusb_d not found, using dummy regulator
[    5.975458] dwc2 fe980000.usb: supply vusb_a not found, using dummy regulator
[    6.077727] dwc2 fe980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
```
```
[root@pikvm /]# journalctl -u kvmd-otg.service
Jan 15 03:12:32 pikvm systemd[1]: Starting PiKVM - OTG setup...
Jan 15 03:12:34 pikvm kvmd-otg[191]: kvmd.apps.otg                     INFO --- Using UDC fe980000.usb
Jan 15 03:12:34 pikvm kvmd-otg[191]: kvmd.apps.otg                     INFO --- Creating gadget 'kvmd' ...
Jan 15 03:12:34 pikvm kvmd-otg[191]: kvmd.apps.otg                     INFO --- MKDIR --- /sys/kernel/config/usb_gadget/kvmd
Jan 15 03:12:34 pikvm kvmd-otg[191]: Traceback (most recent call last):
Jan 15 03:12:34 pikvm kvmd-otg[191]:   File "/usr/bin/kvmd-otg", line 8, in <module>
Jan 15 03:12:34 pikvm kvmd-otg[191]:     sys.exit(main())
Jan 15 03:12:34 pikvm kvmd-otg[191]:              ^^^^^^
Jan 15 03:12:34 pikvm kvmd-otg[191]:   File "/usr/lib/python3.11/site-packages/kvmd/apps/otg/__init__.py", line 348, in main
Jan 15 03:12:34 pikvm kvmd-otg[191]:     options.cmd(config)
Jan 15 03:12:34 pikvm kvmd-otg[191]:   File "/usr/lib/python3.11/site-packages/kvmd/apps/otg/__init__.py", line 212, in _cmd_start
Jan 15 03:12:34 pikvm kvmd-otg[191]:     _mkdir(gadget_path)
Jan 15 03:12:34 pikvm kvmd-otg[191]:   File "/usr/lib/python3.11/site-packages/kvmd/apps/otg/__init__.py", line 50, in _mkdir
Jan 15 03:12:34 pikvm kvmd-otg[191]:     os.mkdir(path)
Jan 15 03:12:34 pikvm kvmd-otg[191]: FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/config/usb_gadget/kvmd'
Jan 15 03:12:34 pikvm systemd[1]: kvmd-otg.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 03:12:34 pikvm systemd[1]: kvmd-otg.service: Failed with result 'exit-code'.
Jan 15 03:12:34 pikvm systemd[1]: Failed to start PiKVM - OTG setup.
Jan 15 03:12:34 pikvm systemd[1]: kvmd-otg.service: Consumed 1.414s CPU time.
```

**Comment by lukedoomer** [comment]
`modproble libcomposite` solves my problem. Thanks for your detailed info about pikvm.

**Comment by Prototyped** [comment]
Ah, I guess I omitted to put that in host setup. Best way is to write a new file in /etc/modules-load.d/kvmd.conf on the host:

```
dwc2
libcomposite
```

I'll make a change to the install.sh to create the file.
